config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :drivers
  devise_for :passengers

  get "/" => "home#top"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :passengers, only: %i(show)
  resources :drivers, only: %i(show)
  resources :orders, only: %i(index create new update edit destroy) do
    get 'contract', on: :member
  end



end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :passenger, optional: true
  belongs_to :driver, optional: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def contract
    @order = Order.find_by(id: params[:id])
    @order.driver_id = current_driver.id
    @order.save
    redirect_to(order_path(@order))
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.passenger_id = current_passenger.id
    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:location, :date_time, :passenger_id, :driver_id, :lat, :lng)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id:"center", size:"50" %>
  </div>

  <%= form.hidden_field :lat, id:"center_lat" %>
  <%= form.hidden_field :lng, id:"center_lng" %>

  <div class="field">
    <%= form.label :date_time %>
    <%= form.datetime_select :date_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Date time</th>
      <th>Passenger</th>
      <th>Driver</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.location %></td>
        <td><%= order.date_time %></td>
        <td><%= order.passenger_id %></td>
        <td><%= order.driver_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

<!-- <%= image_tag('/marker2.png', :id=>"mark") %> -->

<div id="map"></div>

<script type="text/javascript">
    var markers = [];
    function initMap() {
      if (!navigator.geolocation) {
        alert('Geolocation not supported');
        return;
      }

      navigator.geolocation.getCurrentPosition(function(position) {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          },
          zoom: 15
        });

        var geocoder = new google.maps.Geocoder();

        map.addListener( "center_changed", function ( argument ) {
          var centerPosition = map.getCenter();
          document.getElementById('center_lat').value = centerPosition.lat();
          document.getElementById('center_lng').value = centerPosition.lng();

          for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(null);
          }

          marker = new google.maps.Marker({
            position: centerPosition,
            map: map
          });
          markers.push(marker);
        });

        map.addListener( "dragend", function ( argument ) {
          var centerPosition = map.getCenter();
          geocoder.geocode({
            location: centerPosition
          }, function(results, status) {
            if (status !== 'OK') {
              alert('Failed: ' + status);
              return;
            }
            // results[0].formatted_address
            if (results[0]) {
              document.getElementById('center').value = results[0].formatted_address;
            } else {
              alert('No results found');
              return;
            }
          });
        });
      }, function() {
        alert('Geolocation failed!');
        return;
      });
    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= Rails.application.credentials.google_map_key %>&callback=initMap">
</script>

app/views/orders/show.html.erb
<p>
  <strong>Location:</strong>
  <%= @order.location %>
  <div id="latlng" data-lat="<%= @order.lat %>" data-lng="<%= @order.lng %>"></div>
</p>

<p>
  <strong>Date time:</strong>
  <%= @order.date_time %>
</p>

<p>
  <strong>Passenger:</strong>
  <%= @order.passenger.name %>
</p>

<p>
  <strong>Driver:</strong>
  <% if @order.driver_id %>
    <%= @order.driver.name %>
  <% end %>
</p>

<script type="text/javascript">
  function initMap() {
    var lat = Number(document.getElementById("latlng").dataset.lat);
    var lng = Number(document.getElementById("latlng").dataset.lng);

    var orderLocation = {lat: lat, lng: lng};

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: orderLocation
    });

    var marker = new google.maps.Marker({
        position: orderLocation,
        map: map,
    });
  }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= Rails.application.credentials.google_map_key %>&callback=initMap">
</script>

<style type="text/css">
  #map { height: 400px;
    margin-left:auto;
    margin-right:auto;
    text-align:left;
    width: 80%;}
</style>

<% if driver_signed_in? && !@order.driver_id.present? %>
  <%= link_to("受注", contract_order_path(@order)) %>
<% elsif passenger_signed_in? %>

<% else %>
  <p>受注済み</p>
<% end %>

<!-- <%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %> -->

<div id="map"></div>